
# grid parameters
N: 144
Lx: 1
Ly: 2

# simulation control
Ma: 0.35
Re: 400
Pr: 0.697
nperiod: 8 # number of perturbation wavelengths        

# initial conditions
P_inf: 101325.
T_inf1: 300.
T_inf2: 300.
U_inf1:
U_inf2: 

# constants
Rgas: 8314.0

# air (2) and reactant (1) properties
molwt: 28.97

# clustering parameters
grid_beta:  5.0
